on:
  push: 
  pull_request: 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-


      - name: Build with maven
        working-directory: orders-management
        run: mvn clean verify -Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

      
      - name: Upload compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: orders-management/target

   
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
        
      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: orders-management/target
        
      
      - name: Cache SonarCloud package
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Build and analyze with SonarCloud
        working-directory: orders-management
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=Tiezzi96_orders-management -Dsonar.organization=tiezzi96 -Dsonar.host.url=https://sonarcloud.io -Dsonar.junit.reportPaths=target/surefire-reports -Dsonar.java.binaries=target/classes -Dsonar.login=${SONAR_TOKEN}