on:
   push: 
   pull_request: 

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
      -  uses: actions/checkout@v2
      -  name: Set up Java 8
         uses: actions/setup-java@v1
         with:
            java-version: 1.8
      -  name: Build with maven
         working-directory: orders-management
         run: mvn clean verify